# CONFIGURAÇÕES DO BANCO DE DADOS

# URL de conexão com o PostgreSQL
spring.datasource.url=${DB_URL}

# Usuário do banco
spring.datasource.username=${DB_USERNAME}

# Senha do banco
spring.datasource.password=${DB_PASSWORD}

# Driver usado para conectar ao PostgreSQL
spring.datasource.driver-class-name=org.postgresql.Driver


# JPA / HIBERNATE

# Não altera automaticamente as tabelas do banco
spring.jpa.hibernate.ddl-auto=none

# Não exibe os comandos SQL no console
spring.jpa.show-sql=false

# Fecha a conexão com o banco após cada operação
spring.jpa.open-in-view=false


# LOGS

# Mostra apenas erros do Hibernate
logging.level.org.hibernate=ERROR

# Esconde informações do pool de conexões
logging.level.org.hibernate.orm.connections.pooling=ERROR


# SERVER

# Define a porta da aplicação
server.port=8080