CREATE TABLE professor
(
        id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        nome            VARCHAR(150) NOT NULL,
        codigo          VARCHAR(30),
        cpf             VARCHAR(11)  NOT NULL,
        matricula       VARCHAR(30)  NOT NULL,
        regime_contrato VARCHAR(20)  NOT NULL,
        regime_juridico VARCHAR(20),
        status          VARCHAR(20)  NOT NULL,
        titulacao       VARCHAR(30),
        CONSTRAINT uk_professor_cpf UNIQUE (cpf),
        CONSTRAINT uk_professor_matricula UNIQUE (matricula),
        CONSTRAINT ck_professor_cpf CHECK (cpf ~ '^[0-9]{11}$')
);