CREATE EXTENSION IF NOT EXISTS pg_trgm;
CREATE TABLE curso (
    id      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome    VARCHAR(150) NOT NULL,
    turno   VARCHAR(5)   NOT NULL,
    unidade VARCHAR(50)  NOT NULL DEFAULT 'FATEC Zona Leste',
    sigla   VARCHAR(3)   NOT NULL,
    CONSTRAINT ck_curso_turno CHECK (turno IN ('MANHA', 'TARDE', 'NOITE')),
    CONSTRAINT ck_curso_nome CHECK (nome = btrim(nome) AND nome <> ''),
    CONSTRAINT ck_curso_sigla CHECK (btrim(sigla) <> '')
);

CREATE UNIQUE INDEX uk_curso_unidade_sigla_upper ON curso (unidade, upper(sigla));
CREATE UNIQUE INDEX uk_curso_unidade_nome_lower ON curso (unidade, lower(nome));

