CREATE TABLE curso (
    id      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome    VARCHAR(150) NOT NULL,
    turno   VARCHAR(5)   NOT NULL,
    unidade VARCHAR(50)  NOT NULL DEFAULT 'FATEC Zona Leste',
    sigla   VARCHAR(3)   NOT NULL,
    CONSTRAINT ck_curso_turno CHECK (turno IN ('MANHA', 'TARDE', 'NOITE')),
    CONSTRAINT ck_curso_nome CHECK (nome = btrim(nome) AND nome <> ''),
    CONSTRAINT ck_curso_sigla CHECK (btrim(sigla) <> ''),
    CONSTRAINT ck_curso_sigla_letras CHECK (sigla ~ '^[A-Za-z]+$')
);

CREATE UNIQUE INDEX uk_curso_unidade_nome_turno_lower ON curso (unidade, lower(nome), turno);
CREATE UNIQUE INDEX uk_curso_unidade_sigla_turno_upper ON curso (unidade, upper(sigla), turno);