CREATE EXTENSION IF NOT EXISTS pg_trgm;

CREATE TABLE disciplina (
    id      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    codigo  VARCHAR(30)  NOT NULL,
    sigla   VARCHAR(8)   NOT NULL,
    nome    VARCHAR(150) NOT NULL,

    CONSTRAINT uk_disciplina_codigo UNIQUE (codigo),

    CONSTRAINT ck_disciplina_codigo_not_blank CHECK (btrim(codigo) <> ''),
    CONSTRAINT ck_disciplina_sigla_not_blank CHECK (btrim(sigla) <> ''),
    CONSTRAINT ck_disciplina_nome_not_blank CHECK (btrim(nome) <> ''),

    CONSTRAINT ck_disciplina_sigla_letras CHECK (sigla ~ '^[A-Za-z]+$'),

    CONSTRAINT ck_disciplina_codigo_sigla_diferentes CHECK (upper(codigo) <> upper(sigla))
);


CREATE INDEX idx_disciplina_nome_trgm ON disciplina USING GIN (nome gin_trgm_ops);
CREATE INDEX idx_disciplina_codigo ON disciplina (codigo);
CREATE INDEX idx_disciplina_sigla ON disciplina (sigla);