CREATE EXTENSION IF NOT EXISTS pg_trgm;

CREATE TABLE disciplina(
    id      BIGINT  GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    codigo  VARCHAR(30) NOT NULL,
    sigla   VARCHAR(8) NOT NULL,
    nome    VARCHAR(150) NOT NULL,
    CONSTRAINT uk_disciplina_codigo UNIQUE (codigo)
);

CREATE INDEX idx_disciplina_nome_trgm ON disciplina USING GIN (nome gin_trgm_ops);
