CREATE TABLE periodo_letivo (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    semestre    INTEGER NOT NULL,
    ano         INTEGER NOT NULL,
    data_inicio DATE    NOT NULL,
    data_fim    DATE    NOT NULL,

    CONSTRAINT ck_periodo_letivo_semestre CHECK (semestre IN (1, 2)),
    CONSTRAINT ck_periodo_letivo_ano CHECK (ano BETWEEN 2000 AND 2050),
    CONSTRAINT ck_periodo_letivo_datas CHECK (data_inicio < data_fim),
    CONSTRAINT uk_periodo_letivo_ano_semestre UNIQUE (ano, semestre)
);