CREATE TABLE grade (
    id                      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    professor_id            BIGINT NOT NULL,
    periodo_letivo_id       BIGINT NOT NULL,
    semanal                 NUMERIC(6, 2),
    mensal                  NUMERIC(6, 2),
    total                   NUMERIC(6, 2),
    created_at              TIMESTAMP    NOT NULL DEFAULT now(),
    updated_at              TIMESTAMP    NOT NULL DEFAULT now(),

    CONSTRAINT fk_grade_professor FOREIGN KEY (professor_id) REFERENCES professor (id) ON DELETE RESTRICT,
    CONSTRAINT fk_grade_periodo FOREIGN KEY (periodo_letivo_id) REFERENCES periodo_letivo (id) ON DELETE RESTRICT
);